new workflow

diff --git a/.github/workflows/url.yml b/.github/workflows/url.yml
--- a/.github/workflows/url.yml
+++ b/.github/workflows/url.yml
@@ -14,9 +14,12 @@ jobs:
     - uses: actions/checkout@v1
     - name: check for image url
       run: |
-        grep -lr 's3.amazonaws.com'
-        # if: failure()
-        if [grep -lr 's3.amazonaws.com' === 'true']
-        then 
-          echo grep is true
-        # echo grep is false
+        if grep -lrq 's3.amazonaws.com' . ; then echo "s3 references found"; exit 1; else echo "no s3 references found"; fi
+
+
+        # grep -lr 's3.amazonaws.com'
+        # # if: failure()
+        # if [grep -lr 's3.amazonaws.com' === 'true']
+        # then 
+        #   echo grep is true
+        # # echo grep is false
